version: '3.7'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=tminas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=desafio_globotech_1
    volumes:
      - pgdata:/data/postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: desafio_globotech_1
    ports:
      - 3080:3080
    volumes:
      - .:/usr/apps
    links: 
      - db
    depends_on:
      - db


volumes:
  pgdata:
    driver: local